stages:
  - build
  - deploy-frontend

variables:
  AWS_ACCOUNT_ID: "$AWS_ACCOUNT_ID"
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: "monz"
  ECR_IMAGE_TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  DOCKER_BUILD_IMAGE: "docker:latest"
  DOCKER_BUILD_TAG: "$CI_COMMIT_REF_NAME"

before_script:
  - export PATH=$PATH:/usr/local/bin

docker_build_push:
  stage: build
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  services:
    - name: docker:dind
  script:
    - echo "building flask image"
    - export DOCKER_HOST=tcp://docker:2375
    - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$ECR_IMAGE_TAG backend/
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$ECR_IMAGE_TAG
  only:
    - ignore-now

pages:
  image: node:lts
  stage: deploy-frontend
  variables:
    GIT_STRATEGY: none
    PUBLIC_URL: https://apps-themonz-3f6f07533c6e2514c588f61486cf485ee35e9b6c32ca58a286.gitlab.io
  script:
    - mkdir public
    - cd frontend
    - yarn install
    - yarn build
    - mv build ../public
  artifacts:
    paths:
      - public