name: publish frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: |
          cd frontend
          npm install
      - run: |
          cd frontend
          npm run build
      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: frontend/build

