name: fetchling

on:
  push:
    branches:
      - main

jobs:

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: |
          cd frontend
          npm install
      - run: |
          cd frontend
          npm run build
      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pages
          folder: frontend/build

  build-push-pricefetcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: |
          cd PriceFetcher
          ./gradlew build
      - run: |
          cd PriceFetcher
          docker build -t ${{ github.repository }} .
      - run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}
      - run: docker tag ${{ github.repository }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest
      - run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFULT_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest
